### PR TITLE
Fix infinite loop error when defining protobuf index with large value

### PR DESCRIPTION
**Pull request by whatvn**
(66 for example).

Define protobuf metadata file when field index is big enough, we started
to have infinite loop with field index 66:

```
syntax = "proto2";

message Example
{
    required string id = 1;
    optional string id1 = 2;
    optional string cur = 66;
}
```

1. When calling serializeToString, php zend api `zend_hash_index_find` will
be stuck in infinited loop forever with our `values`, this loop
introduced in zend internal function `zend_hash_index_find_bucket`:

```C
static zend_always_inline Bucket *zend_hash_index_find_bucket(const
HashTable *ht, zend_ulong h)
{
	uint32_t nIndex;
	uint32_t idx;
	Bucket *p, *arData;

	arData = ht->arData;
	nIndex = h | ht->nTableMask;
	idx = HT_HASH_EX(arData, nIndex);
	while (idx != HT_INVALID_IDX) {
		ZEND_ASSERT(idx < HT_IDX_TO_HASH(ht->nTableSize));
		p = HT_HASH_TO_BUCKET_EX(arData, idx);
		if (p->h == h && !p->key) {
			return p;
		}
		idx = Z_NEXT(p->val);
	}
	return NULL;
}

```

Something happens within our hashtables `values` which causes `idx`
bigger than `nHashTableSize`, so if we build php in debug mode,
ZEND_ASSERT will be fail, otherwise, we will stuck in infinite loop
forever.

2. With same protobuf metadata file, if we use protoc-gen-php to gen php
file and then use it like this:

```php
<?php

require_once("BidResponse.php");

$brp = new BidResponse();
// call setCur() first
$brp->setCur("aaa");
$brp->setid(1);
$brp->setid1(2);



$data = $brp->serializeToString();

var_dump($data);

```
we will have problem descibed in *1*. If we use setCur() function first,
infinite loop will be happend inside PHP_METHOD `set()` function, which
is also introduced by zend_hash_index_find descibed in *1*.

This patch rewrite `pb_get_value` to not to use `zend_hash_index_find`, but
looping through our `values` until we find needed index. In our test it
fixed both problem described above.

Looping through `values` can be slow, but in my opinion,
`zend_hash_index_find_bucket` also use loop, this solution removes a
loop and use another loop, so it's ok for me.

### CODE REVIEW

**Comment by serggp** [comment]
@whatvn Thank you for your report and fix. But complexity of your implementation is O(n^2). There might be a better solution for the issue.

**Comment by whatvn** [comment]
I know this implementation may slow down serialization and set "just a little bit", because almost protobuf metadata file won't have so much field to make for loop run forever. 
Actually in my test implementation, in `serializationToString` I dont have to call pb_get_value in order to get field value, but `set` method has to.

**Comment by Tharnum** [comment]
Hi guys.

Just set cur's index to (index_of_id1 + 8 * n) where n is any integer number...

**Comment by Tharnum** [comment]
Check this solution.

```
--- a/protobuf.c
+++ b/protobuf.c
@@ -798,7 +798,8 @@ static int pb_assign_value(zval *this, zval *dst, zval *src, zend_ulong field_nu
                goto fail2;
        }

-       *dst = tmp;
+    //*dst = tmp;
+    ZVAL_COPY_VALUE(dst, &tmp);

        zval_ptr_dtor(&field_descriptors);
        return 0;
```

`*dst = tmp` copies `zval::u2` union that contains `next` member used in the zend_hash_index_find_bucket():
```
idx = Z_NEXT(p->val);
```

More info here: http://jpauli.github.io/2016/04/08/hashtables.html#collisions-resolution

**Comment by whatvn** [comment]
Awesome! I haven't checked but I think this will gonna work. Thank for opening my mind 👍

**Comment by whatvn** [comment]
@serggp what do you think?

**Comment by kenny1002** [comment]
#syntax = "proto2";
message BasePush {
}
enum EmDeviceDataType {
    EDDT_manufatureSvr = 0; 
    EDDT_wxWristBand = 1; 
    EDDT_wxDeviceHtmlChatView = 10001; 
}
message RecvDataPush {
    required BasePush BasePush = 1;
    required bytes Data = 2;
    optional EmDeviceDataType Type = 3; 
}

//php7
 $recvDataPush = new RecvDataPush();
        $recvDataPush->setBasePush(new BasePush());
        $recvDataPush->setData('33078001a224');
        $recvDataPush->setType(EmDeviceDataType::EDDT_manufatureSvr);
        try {
            echo bin2hex($recvDataPush->serializeToString());  //The null value is returned here
        } catch (Exception $e) {
            echo $e->getMessage();
        }
@serggp

**Pull request closed without merging**
